config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all.order("created_at DESC")
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
      def book_params
        params.require(:book).permit(:title, :description, :author)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f|%>
  <%= f.input :title , label: "Book Title" %>
 
  <%= f.input :description , label: "Book Description" %>
  <%= f.input :author , label: "Book Author" %>

  <%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<% @books.each do |book| %>
  <h2><%= book.title %></h2>
<% end %>

<%= link_to "Add Book", new_book_path%>

app/views/books/new.html.erb
<h1> New Book </h1>

<%= render 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>